const SCANNER_STATE = {
    START: 'SCANNER_STATE_START',
    DIGIT: 'SCANNER_STATE_DIGIT',
    COMMENT: 'SCANNER_STATE_COMMENT',
    SEPARATOR: 'SCANNER_STATE_SEPARATOR',
    IDENTIFIER: 'SCANNER_STATE_IDENTIFIER',
};

const TOKEN_PRE_TYPE = {
    LITERAL: 'TOKEN_PRE_TYPE_LITERAL',
    SEPARATOR: 'TOKEN_PRE_TYPE_SEPARATOR',
    IDENTIFIER: 'TOKEN_PRE_TYPE_IDENTIFIER',
};

const TABLE_TYPE = {
    SERVICE: 'TABLE_TYPE_SERVICE',
    SEPARATOR: 'TABLE_TYPE_SEPARATOR',
    IDENTIFIER: 'TABLE_TYPE_IDENTIFIER',
    LITERAL: 'TABLE_TYPE_LITERAL',
    STANDART: 'TABLE_TYPE_STANDART',
};

module.exports = {
    SCANNER_STATE,
    TOKEN_PRE_TYPE,
    TABLE_TYPE,
};
